### ISSUE TITLE
How to add a room

### ISSUE THREAD

**Issue by Conor-Burns** [Half-Shot/matrix-appservice-discord#271]
so i have installed everything and it seems to work:
bot in docker
`
Oct-28 11:40:01.998 [DiscordAS] verbose: matrix-appservice-bridge [-] PUT https://matrix.conor-burns.com:8448/_matrix/client/r0/presence/%40_discord_239837076864892929%3Amatrix.conor-burns.com/status (@_discord_239837076864892929:matrix.conor-burns.com) HTTP 200 "{}"`
matrix in docker
`
2018-10-28 11:41:42,066 - synapse.access.https.8448 - 302 - INFO - PUT-1935 - - - 8448 - {@_discord_159011914758881280:matrix.conor-burns.com} Processed request: 0.002sec/0.001sec (0.001sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "PUT /_matrix/client/r0/presence/%40_discord_159011914758881280%3Amatrix.conor-burns.com/status?access_token=<redacted>&user_id=%40_discord_159011914758881280%3Amatrix.conor-burns.com HTTP/1.1" "-" [0 dbevts]`

(not the same presence but it shows that its working)

now if i do #_discord_GUILD_CHANNEL in a matrix room nothing happenes :/
how am i supposed to bridge channels and rooms?

**Comment by Half-Shot** [comment]
>now if i do #_discord_GUILD_CHANNEL in a matrix room nothing happenes :/
how am i supposed to bridge channels and rooms?

You are meant to *join* the alias #_discord_guild_channel:yourdomain.com

**Comment by Conor-Burns** [comment]
ok im stupid :D but if i do that this happens `Room alias #_discord_239841341712891914_506067682261598208:matrix.conor-burns.com not found (M_NOT_FOUND)`

**Comment by Half-Shot** [comment]
That sounds like you've not restarted synapse, or you've not given it the discord registration, or discord can't find the guild/channel and is throwing an error.

**Comment by Conor-Burns** [comment]
```
namespaces:
  users:
    - exclusive: true
      regex: '@_discord_.*'
  aliases:
    - exclusive: true
      regex: '#_discord_.*'
  rooms: []
url: 'http://localhost:9005'
sender_localpart: _discord_bot
rate_limited: false
protocols:
  - discord
```
this is the registration file and both synapse and the bot have been restartet.
`https://discordapp.com/channels/239841341712891914/239841341712891914` this is the discord url and im trying to join this `#_discord_239841341712891914_239841341712891914:matrix.conor-burns.com`

**Comment by Sorunome** [comment]
what is your `config.yaml`? Be sure to also remove the bot keys and stuff there!

**Comment by Conor-Burns** [comment]
```
# This is a sample of the config file showing all avaliable options.
# Where possible we have documented what they do, and all values are the
# default values.

bridge:
  # Domain part of the bridge, e.g. matrix.org
  domain: "matrix.conor-burns.com"
  # This should be your publically facing URL because Discord may use it to
  # fetch media from the media store.
  homeserverUrl: "https://matrix.conor-burns.com:8448"
  # Interval at which to process users in the 'presence queue'. If you have
  # 5 users, one user will be processed every 500 milliseconds according to the
  # value below. This has a minimum value of 250.
  # WARNING: This has a high chance of spamming the homeserver with presence
  # updates since it will send one each time somebody changes state or is online.
  presenceInterval: 500
  # Disable setting presence for 'ghost users' which means Discord users on Matrix
  # will not be shown as away or online.
  disablePresence: false
  # Disable sending typing notifications when somebody on Discord types.
  disableTypingNotifications: false
  # Disable parsing discord usernames out of matrix messages so
  # that it highlights discord users.
  # WARNING: Not always 100% accurate, but close enough usually.
  disableDiscordMentions: false
  # Disable deleting messages on Discord if a message is redacted on Matrix.
  disableDeletionForwarding: false
  # Enable users to bridge rooms using !discord commands. See
  # https://t2bot.io/discord for instructions.
  enableSelfServiceBridging: false
  # For both below, a space is inserted after @ to stop the mentions working.
  # Disable relaying @everyone to Discord. Non-puppeted users can abuse this.
  disableEveryoneMention: false
  # Disable relaying @here to Discord. Non-puppeted users can abuse this.
  disableHereMention: false
# Authentication configuration for the discord bot.
auth:
  clientID: "1234"
  botToken: "string"
logging:
  # What level should the logger output to the console at.
  console: "silly" #silly, verbose, info, http, warn, error, silent
  lineDateFormat: "MMM-D HH:mm:ss.SSS" # This is in moment.js format
  files:
    - file: "debug.log"
      disable:
        - "PresenceHandler" # Will not capture presence logging
    - file: "warn.log" # Will capture warnings
      level: "warn"
    - file: "botlogs.log" # Will capture logs from DiscordBot
      level: "info"
      enable:
        - "DiscordBot"
database:
  userStorePath: "user-store.db"
  roomStorePath: "room-store.db"
  # You may either use SQLite or Postgresql for the bridge database, which contains
  # important mappings for events and user puppeting configurations.
  # Use the filename option for SQLite, or connString for Postgresql.
  # If you are migrating, see https://github.com/Half-Shot/matrix-appservice-discord/blob/master/docs/howto.md#migrate-to-postgres-from-sqlite
  # WARNING: You will almost certainly be fine with sqlite unless your bridge
  # is in heavy demand and you suffer from IO slowness.
  filename: "discord.db"
  # connString: "postgresql://user:password@localhost/database_name"
room:
  # Set the default visibility of alias rooms, defaults to "public".
  # One of: "public", "private"
  defaultVisibility: "public"
channel:
    # Pattern of the name given to bridged rooms.
    # Can use :guild for the guild name and :name for the channel name.
    namePattern: "[Discord] :guild :name"
    # Changes made to rooms when a channel is deleted.
    deleteOptions:
       # Prefix the room name with a string.
       #namePrefix: "[Deleted]"
       # Prefix the room topic with a string.
       #topicPrefix: "This room has been deleted"
       # Disable people from talking in the room by raising the event PL to 50
       disableMessaging: false
       # Remove the discord alias from the room.
       unsetRoomAlias: true
       # Remove the room from the directory.
       unlistFromDirectory: true
       # Set the room to be unavaliable for joining without an invite.
       setInviteOnly: true
       # Make all the discord users leave the room.
       ghostsLeave: true
limits:
    # Delay in milliseconds between discord users joining a room.
    roomGhostJoinDelay: 6000
    # Delay in milliseconds before sending messages to discord to avoid echos.
    # (Copies of a sent message may arrive from discord before we've
    # fininished handling it, causing us to echo it back to the room)
    discordSendDelay: 750

```

**Comment by Conor-Burns** [comment]
```
bridge:
  domain: "matrix.conor-burns.com"
  homeserverUrl: "https://matrix.conor-burns.com:8448"
  presenceInterval: 500
  disablePresence: false
  disableTypingNotifications: false
  disableDiscordMentions: false
  disableDeletionForwarding: false
  enableSelfServiceBridging: false
  disableEveryoneMention: false
  disableHereMention: false
auth:
  clientID: "1234"
  botToken: "string"
logging:
  console: "silly" #silly, verbose, info, http, warn, error, silent
  lineDateFormat: "MMM-D HH:mm:ss.SSS" # This is in moment.js format
  files:
    - file: "debug.log"
      disable:
        - "PresenceHandler" # Will not capture presence logging
    - file: "warn.log" # Will capture warnings
      level: "warn"
    - file: "botlogs.log" # Will capture logs from DiscordBot
      level: "info"
      enable:
        - "DiscordBot"
database:
  userStorePath: "user-store.db"
  roomStorePath: "room-store.db"
  filename: "discord.db"
room:
  defaultVisibility: "public"
channel:
    namePattern: "[Discord] :guild :name"
    deleteOptions:
       disableMessaging: false
       unsetRoomAlias: true
       unlistFromDirectory: true
       setInviteOnly: true
       ghostsLeave: true
limits:
    roomGhostJoinDelay: 6000
    discordSendDelay: 750

```
(without the comments)
