### ISSUE TITLE
Errors after inviting.

### ISSUE THREAD

**Issue by commagray** [Half-Shot/matrix-appservice-discord#355]
After inviting @_discord_bot:mle.party to a room on matrix.org I get:
```
Dec-27 02:56:30.122 [MatrixRoomHandler] info: Received invite for @_discord_bot:mle.party in room !RjkulZSbPcxSbXbNCp:matrix.org
Dec-27 02:56:30.123 [MatrixRoomHandler] info: Accepting invite for bridge bot
Dec-27 02:56:30.165 [MatrixRoomHandler] error: Error joining room !RjkulZSbPcxSbXbNCp:matrix.org as @_discord_bot:mle.party
Dec-27 02:56:30.167 [MatrixRoomHandler] error: { [M_NOT_FOUND: Profile was not found]
  errcode: 'M_NOT_FOUND',
  name: 'M_NOT_FOUND',
  message: 'Profile was not found',
  data: { errcode: 'M_NOT_FOUND', error: 'Profile was not found' },
  httpStatus: 404 }
Dec-27 02:56:31.187 [MatrixRoomHandler] error: Error joining room !RjkulZSbPcxSbXbNCp:matrix.org as @_discord_bot:mle.party
Dec-27 02:56:31.187 [MatrixRoomHandler] error: { [M_NOT_FOUND: Profile was not found]
  errcode: 'M_NOT_FOUND',
  name: 'M_NOT_FOUND',
  message: 'Profile was not found',
  data: { errcode: 'M_NOT_FOUND', error: 'Profile was not found' },
  httpStatus: 404 }
Dec-27 02:57:01.221 [MatrixRoomHandler] error: Error joining room !RjkulZSbPcxSbXbNCp:matrix.org as @_discord_bot:mle.party
Dec-27 02:57:01.222 [MatrixRoomHandler] error: { [M_NOT_FOUND: Profile was not found]
  errcode: 'M_NOT_FOUND',
  name: 'M_NOT_FOUND',
  message: 'Profile was not found',
  data: { errcode: 'M_NOT_FOUND', error: 'Profile was not found' },
  httpStatus: 404 }
^C
```

But if invite to mle.party room everything is OK. It happens on dirty and on clean database. 

Commit of used bridge: `ed12b5cbc06826343364bd9a530b3006fbb89c12`.

Config:
```
bridge:
  domain: "mle.party"
  homeserverUrl: "https://mle.party:8448"
  presenceInterval: 500
  disablePresence: true
  disableTypingNotifications: true
  disableDiscordMentions: false
  disableDeletionForwarding: false
  enableSelfServiceBridging: true
  disableEveryoneMention: false
  disableHereMention: false
auth:
  clientID: "bla"
  secret: "bla"
  botToken: "bla"
logging:
  level: "warn"
  lineDateFormat: "MMM-D HH:mm:ss.SSS"
  files:
    - file: "debug.log"
      disable:
        - "PresenceHandler"
    - file: "warn.log"
      level: "warn"
    - file: "botlogs.log"
      level: "info"
      enable:
        - "DiscordBot"
database:
  filename: "discord.db"
  userStorePath: "user-store.db"
  roomStorePath: "room-store.db"
#  connString: "postgresql://bla:bla@localhost/bla"
room:
  defaultVisibility: "public"
channel:
    namePattern: "[Discord] :guild :name"
    deleteOptions:
       disableMessaging: false
       unsetRoomAlias: true
       unlistFromDirectory: true
       setInviteOnly: true
       ghostsLeave: true
limits:
    roomGhostJoinDelay: 6000
    discordSendDelay: 750
```
