### ISSUE TITLE
Application service has not registered this user

### ISSUE THREAD

**Issue by floviolleau** [Half-Shot/matrix-appservice-discord#54]
Hi,

I successfully installed the bridge, configured it and run it. I configurated the HS.

I can see the room in matrix and the bot user.
I have the bot in discord.
I typed a message in matrix but it never comes in the discord chat and reciprocally
The bridge is running
The HS is running and has registered the bridge at startup
Here is my configuration (config.yaml):

```
bridge:
  domain: "exemple.org"
  homeserverUrl: "https://example.org"
  disablePresence: false
  disableTypingNotifications: false
  disableDiscordMentions: false
auth:
  clientID: "blablabla" # Get from discord
  secret: "blablabla"
  botToken: "blablabla"
logging:
  level: "warn" #silly, verbose, info, http, warn, error
database:
  filename: "discord.db"
```

```
verb DiscordBot Bulk presence update
verb matrix-appservice-bridge [-] PUT https://exemple.org/_matrix/client/r0/presence/%40_discord_1074867890098760%3Aexemple.org/status (@_discord_10678998762960:exemple.org) Body: {"presence":"unavailable"}
verb matrix-appservice-bridge [-] PUT https://exemple.org/_matrix/client/r0/presence/%40_discord_3576876567876482%3Aexemple.org/status (@_discord_357656789098776482:exemple.org) Body: {"presence":"online"}
verb matrix-appservice-bridge [-] PUT https://exemple.org/_matrix/client/r0/presence/%40_discord_3576366789876482%3Aexemple.org/status (@_discord_3576368765678909:exemple.org) HTTP 403 Error: {"errcode":"M_FORBIDDEN","error":"Application service has not registered this user"}
verb matrix-appservice-bridge [-] PUT https://exemple.org/_matrix/client/r0/presence/%40_discord_1074887656789060%3Aexemple.org/status (@_discord_10876789876789:exemple.org) HTTP 200 {}
```
Any idea about `Application service has not registered this user` 403 error?
Thanks for your help.
