### ISSUE TITLE
Docker Container Ignores UID/GID EnvVars

### ISSUE THREAD

**Issue by electricOzone** [Half-Shot/matrix-appservice-discord#615]
When using the Docker container, gIven a UID and GID the bridge always runs as root. It should run as the specified user.

docker-compose.yml:
```
  matrix-appservice-discord:
    image: halfshot/matrix-appservice-discord
    container_name: matrix-appservice-discord
    ports:
        - 9005:9005
    volumes:
      - /opt/docker/matrix-appservice-discord:/data
    environment:
      - UID=999
      - GID=999
    restart: always
```

```
user@server:/opt/docker$ ps aux | grep discord
root       537  0.7  2.9 389524 59288 ?        Ssl  Aug18 149:40 node /build/src/discordas.js -p 9005 -c /data/config.yaml -f /data/discord-registration.yaml
```

**Comment by electricOzone** [comment]
Closing as there is a more standard way to achieve this, by specifying the UID and GID as a string value to the key user:

```
  matrix-appservice-discord:
    image: halfshot/matrix-appservice-discord
    container_name: matrix-appservice-discord
    ports:
        - 9005:9005
    volumes:
      - /opt/docker/matrix-appservice-discord:/data
    user: "999:999"
    restart: always
```
