### ISSUE TITLE
Logging cannot be set to silent in all cases

### ISSUE THREAD

**Issue by electricOzone** [Half-Shot/matrix-appservice-discord#621]
Regarding the logging section of config.yaml:

```
logging:
  # What level should the logger output to the console at.
  console: "error" #silly, verbose, info, http, warn, error, silent
  lineDateFormat: "MMM-D HH:mm:ss.SSS" # This is in moment.js format
  files:
    - file: "debug.log"
      disable:
        - "PresenceHandler" # Will not capture presence logging
    - file: "warn.log" # Will capture warnings
      level: "warn"
    - file: "botlogs.log" # Will capture logs from DiscordBot
      level: "info"
      enable:
        - "DiscordBot"
```

It is not possible to set warn.log or botlogs.log to silent. Debug.log also can't be disabled. This is all in the interest of preventing the server from generating unnecessary records that could pose a privacy risk. I understand Discord has their own privacy policies, but as sysadmins, we should do our best to limit privacy risks caused by unnecessary logging in production.
