### ISSUE TITLE
Get 'Application service has not registered this user' error after successful setup

### ISSUE THREAD

**Issue by zaharzagrava** [Half-Shot/matrix-appservice-discord#748]
First of all, I created discord application and discord bot (with Admin rights just in case), then I setup my config file:

``` yaml
bridge:
  # Domain part of the bridge, e.g. matrix.org
  domain: "d03f-37-139-160-239.ngrok.io"
  # This should be your publicly-facing URL because Discord may use it to
  # fetch media from the media store.
  homeserverUrl: "http://d03f-37-139-160-239.ngrok.io"
  # The TCP port on which the appservice runs on.
  port: 9005
  # Interval at which to process users in the 'presence queue'. If you have
  # 5 users, one user will be processed every 500 milliseconds according to the
  # value below. This has a minimum value of 250.
  # WARNING: This has a high chance of spamming the homeserver with presence
  # updates since it will send one each time somebody changes state or is online.
  presenceInterval: 500
  # Disable setting presence for 'ghost users' which means Discord users on Matrix
  # will not be shown as away or online.
  disablePresence: false
  # Disable sending typing notifications when somebody on Discord types.
  disableTypingNotifications: false
  # Disable deleting messages on Discord if a message is redacted on Matrix.
  disableDeletionForwarding: false
  # Disable portal bridging, where Matrix users can search for unbridged Discord
  # rooms on their Matrix server.
  disablePortalBridging: false
  # Enable users to bridge rooms using !discord commands. See
  # https://t2bot.io/discord for instructions.
  enableSelfServiceBridging: false
  # Disable sending of read receipts for Matrix events which have been
  # successfully bridged to Discord.
  disableReadReceipts: false
  # Disable Join Leave echos from matrix
  disableJoinLeaveNotifications: false
  # Disable Invite echos from matrix
  disableInviteNotifications: false
  # Auto-determine the language of code blocks (this can be CPU-intensive)
  determineCodeLanguage: false
# Authentication configuration for the discord bot.
auth:
  # This MUST be a string (wrapped in quotes)
  clientID: "913697282707308565"
  botToken: "I_HAVE_PASTED_MY_BOT_TOKEN_HERE"
  # You must enable "Privileged Gateway Intents" in your bot settings on discord.com (e.g. https://discord.com/developers/applications/913697282707308565/bot)
  # for this to work
  usePrivilegedIntents: true
logging:
  # What level should the logger output to the console at.
  console: "verbose" #silly, verbose, info, http, warn, error, silent
  lineDateFormat: "MMM-D HH:mm:ss.SSS" # This is in moment.js format
  files:
    - file: "debug.log"
      disable:
        - "PresenceHandler" # Will not capture presence logging
    - file: "warn.log" # Will capture warnings
      level: "warn"
    - file: "botlogs.log" # Will capture logs from DiscordBot
      level: "info"
      enable:
        - "DiscordBot"
database:
  # You may either use SQLite or Postgresql for the bridge database, which contains
  # important mappings for events and user puppeting configurations.
  # Use the filename option for SQLite, or connString for Postgresql.
  # If you are migrating, see https://github.com/Half-Shot/matrix-appservice-discord/blob/master/docs/howto.md#migrate-to-postgres-from-sqlite
  # WARNING: You will almost certainly be fine with sqlite unless your bridge
  # is in heavy demand and you suffer from IO slowness.
  filename: "discord.db"
  # connString: "postgresql://user:password@localhost/database_name"
room:
  # Set the default visibility of alias rooms, defaults to "public".
  # One of: "public", "private"
  defaultVisibility: "public"
channel:
    # Pattern of the name given to bridged rooms.
    # Can use :guild for the guild name and :name for the channel name.
    namePattern: "[Discord] :guild :name"
    # Changes made to rooms when a channel is deleted.
    deleteOptions:
       # Prefix the room name with a string.
       #namePrefix: "[Deleted]"
       # Prefix the room topic with a string.
       #topicPrefix: "This room has been deleted"
       # Disable people from talking in the room by raising the event PL to 50
       disableMessaging: false
       # Remove the discord alias from the room.
       unsetRoomAlias: true
       # Remove the room from the directory.
       unlistFromDirectory: true
       # Set the room to be unavailable for joining without an invite.
       setInviteOnly: true
       # Make all the discord users leave the room.
       ghostsLeave: true
limits:
    # Delay in milliseconds between discord users joining a room.
    roomGhostJoinDelay: 6000
    # Lock timeout in milliseconds before sending messages to discord to avoid
    # echos. Default is rather high as the lock will most likely time out
    # before anyways.
    # echos = (Copies of a sent message may arrive from discord before we've
    # fininished handling it, causing us to echo it back to the room)
    discordSendDelay: 1500
    # Set a maximum of rooms to be bridged.
    # roomCount: 20
ghosts:
    # Pattern for the ghosts nick, available is :nick, :username, :tag and :id
    nickPattern: ":nick"
    # Pattern for the ghosts username, available is :username, :tag and :id
    usernamePattern: ":username#:tag"
# Prometheus-compatible metrics endpoint
metrics:
    enable: false
    port: 9001
    host: "127.0.0.1"
```

I have obtained bot token from here by clicking on `Click to reveal token` in `Bot` tab of the discord developer portal:

![image](https://user-images.githubusercontent.com/31539383/143594624-ddf58f05-2b32-4a5d-b698-0624e0758fbd.png)

I got my client id from Discord Developer Portal -> `General Infromation` tab:

![image](https://user-images.githubusercontent.com/31539383/143594793-f8b8c9e2-3601-42d7-8a67-6527958db789.png)

Then I setup my local synapse server following [these instructions](https://hub.docker.com/r/matrixdotorg/synapse/). I executed `docker run -it --rm   --mount type=volume,src=synapse-data,dst=/data   -e SYNAPSE_SERVER_NAME=my.matrix.host   -e SYNAPSE_REPORT_STATS=yes   matrixdotorg/synapse:latest generate` to generate `homeserver.yaml`, then I generated `docker-registration.yaml` and pasted it under `app_service_config_files`. Then I started my synapse server:

`docker run --rm --name synapse --mount type=volume,src=synapse-data,dst=/data -p 8008:8008 matrixdotorg/synapse:latest`

Then I executed `ngrok http 8008` to proxy my synapse onto a remote url, then `npm run addbot`, got the link and invited the bot into my chat, then finally `npm run start` to start the bridge. I know that it works, because when I start it with `npm run start` the bot is marked as being online in my chat, but the problem is that it constantly returns these errors while running:

```
Nov-26 16:28:30.662 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:31.172 [bot-sdkMatrixHttpClient (REQ-301)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:31.173 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:31.660 [bot-sdkMatrixHttpClient (REQ-302)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:31.660 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:32.162 [bot-sdkMatrixHttpClient (REQ-303)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:32.163 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:32.662 [bot-sdkMatrixHttpClient (REQ-304)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:32.662 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:33.159 [bot-sdkMatrixHttpClient (REQ-305)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:33.160 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:33.663 [bot-sdkMatrixHttpClient (REQ-306)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:33.664 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:34.174 [bot-sdkMatrixHttpClient (REQ-307)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:34.175 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:34.679 [bot-sdkMatrixHttpClient (REQ-308)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:34.679 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:35.173 [bot-sdkMatrixHttpClient (REQ-309)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:35.173 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:35.660 [bot-sdkMatrixHttpClient (REQ-310)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:35.662 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:36.167 [bot-sdkMatrixHttpClient (REQ-311)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:36.168 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:36.667 [bot-sdkMatrixHttpClient (REQ-312)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:36.667 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:37.165 [bot-sdkMatrixHttpClient (REQ-313)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:37.165 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:37.667 [bot-sdkMatrixHttpClient (REQ-314)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:37.673 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:38.165 [bot-sdkMatrixHttpClient (REQ-315)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:38.165 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:38.668 [bot-sdkMatrixHttpClient (REQ-316)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:38.669 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:39.166 [bot-sdkMatrixHttpClient (REQ-317)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:39.166 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:39.668 [bot-sdkMatrixHttpClient (REQ-318)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:39.669 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:40.170 [bot-sdkMatrixHttpClient (REQ-319)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:40.171 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:40.669 [bot-sdkMatrixHttpClient (REQ-320)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:40.670 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:41.170 [bot-sdkMatrixHttpClient (REQ-321)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:41.171 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:41.669 [bot-sdkMatrixHttpClient (REQ-322)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:41.670 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:42.167 [bot-sdkMatrixHttpClient (REQ-323)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:42.169 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:42.666 [bot-sdkMatrixHttpClient (REQ-324)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:42.667 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:43.173 [bot-sdkMatrixHttpClient (REQ-325)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:43.173 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
Nov-26 16:28:43.666 [bot-sdkMatrixHttpClient (REQ-326)] error: [
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_526645051195916298:d03f-37-139-160-239.ngrok.io)'
  }
]
Nov-26 16:28:43.666 [PresenceHandler] warn: Could not update Matrix presence for 526645051195916298
```
